### ISSUE TITLE
Use .env file for git development

### ISSUE THREAD

**Issue by souldessin** [macxcool/meals-app#1]
Hello, hello; I wanted to get you my thoughts that you had asked for on Fedi. First off, I'll say that the code looks clean. Second, I'll say that a lot of my experience is older, as in pushing for speed and efficiency rather than ultra quick development with a million libraries (that likely have a bunch of security issues). Personally, I prefer vanilla JS and I'll often just pull sections from other libraries, as opposed to importing the whole library (effects libraries are the best for this, when CSS can't do it). Enough about that, on to my first recommendation.

JS is a little different, but when developing with git, be sure to use an env file. Things like Docker are made to look for a `.env` file. Then you put the `.env` in the `.gitignore` file and create a `.env.example` file that has placeholders for things like passwords, API urls, and keys. This way, you can have your dev keys on one system and your production keys on the server, but none of them end up in your repo.

A simple method of making a JS version of the an `.env` file is to make `env.js` & `env.js.example` files and just add them like you did the other libraries.

Also, remember that JS isn't the best for security with keys. The whole having to have the files on the client pc and all. Some little bit of server side script is the easiest to handle API calls. Just be sure to **_always_** parse & sanitize incoming requests.

**Comment by macxcool** [comment]
Yeah. I was wondering how it was best to do that. I work with PHP where it's much easier to hide things from the client pc. The 'env' file is a good idea. I use environment variables for things like that in PowerShell, too, to keep them out of the hands of anyone who can read the script.

Thank you very much for your feedback. I really appreciate it. Doing and getting good quality criticism is the best way of learning, I think.

**Comment by macxcool** [comment]
I think I may use some PHP or SQLite instead of the API I'm using now.

**Comment by macxcool** [comment]
OK. I've added env.js and env.example.js into the mix.
