### ISSUE TITLE
Fully naming all variables

### ISSUE THREAD

**Issue by souldessin** [macxcool/meals-app#2]
In the `js/storage.js` file, you have a function called `loadDataFromAPI()` and another `loadLODataFromAPI()`. Many company dev teams are really pushing the absolute full naming convention.

So, something more like `loadMealDataFromAPI()` & `loadLeftOverDataFromAPI()` would be looked at as more appropriate.

**Comment by macxcool** [comment]
Good point. I guess I got lazy when I expanded the functionality to include leftovers ;-). It's probably a good idea. After all, with an IDE you aren't typing those all out when you use them anyway. There's no real reason for terseness.

**Comment by macxcool** [comment]
Implemented
