### ISSUE TITLE
Code is *NOT* comments

### ISSUE THREAD

**Issue by souldessin** [macxcool/meals-app#3]
I'll spare you my rant on this, but in short, I don't believe that code can be made in a way that it can completely remove the need for comments. That said, there are some dev groups that believe that, and you may cross them one day. From my experience, any team that works with that mentality will quickly outgrow its worth and end up with spaghetti code and a boat load of fixes.

First, my recommendation for your code here. I prefer that all of my classes/libraries have a short comment section at the top that describes the general of the class/library (including the functions/methods inside). It can seam like a bit of double work making sure that there is a little list of functions at the top of a file, but it really helps when looking for things.

Second, I *always* put a comment section in each function that tells what it expects and gives. This includes what type of results are expected and returned. For example, `// Expects a boolean, returns a boolean` or `//Expects a string, returns a boolean` and so on. I personally have this requirement due to one time working with a "code is comments" group that would take strings from the user, pass them to a function that expected a boolean, then return a number. All of this was because `0` & `1` could work for all of those, but none of them would take to time to read their code (that acted as comments) to figure it out. I became a problem, when I had to insert a class in the middle of the process to check if a credit card was fraudulent or not. Because they wanted it done right away, I had to make multiple dataset changes for things to work. It would have taken me adjusting 5 different library files just to get everything on the same dataset page.

Moral of the story, just put a comment reminding you what is needed and what will be returned. I have many more stories on that nonsense.

**Comment by macxcool** [comment]
;-) Yeah. I wasn't thinking about anyone else reading this when I started. Very good idea, though. In my Production scripts I tend to be very verbose. I like your 'Expects' and 'Returns', though, especially with vanilla js where typing isn't strictly enforced..

**Comment by macxcool** [comment]
Implemented
