### ISSUE TITLE
Strictly using camel or snake casing

### ISSUE THREAD

**Issue by souldessin** [macxcool/meals-app#4]
I also noticed you have a variable in the `js/storage.js` file on line `71` that doesn't have camel casing. Some people are extra strict about that kind of thing. It doesn't hurt much, if anything at all, when programming with classes, but I've crossed some companies that are sort of stupid about it. Almost religiously so.

**Comment by macxcool** [comment]
Yeah. I try to use camel case everywhere, but sometimes I miss something. Consistency is good! Actually, though, I think of 'leftovers' as a single word, so it would be proper in camel case.
