### ISSUE TITLE
Switch, if-else, IF If if iF...

### ISSUE THREAD

**Issue by souldessin** [macxcool/meals-app#5]
This is more just to let you know the landscape out there, but there are some who think that everything should only be one if and it self terminates then you make all the one-ifs you need. As for myself, switches and if-elses are A-OK. I think that they are easier to read and manage.

**Comment by macxcool** [comment]
I agree. I do a lot of PowerShell scripting on Windows and I really like using 'switch'. I usually try to make my code more readable if I can.
