### ISSUE TITLE
Deleting over commenting out

### ISSUE THREAD

**Issue by souldessin** [macxcool/meals-app#6]
With git, dev teams really prefer to delete over commenting out something. Just be sure to make some really good & descriptive comments when committing. It is even better to only have one commit per deleted code, so that you can roll that stuff back, if needed.

If there is something that may need to be referenced, I would recommend using the wiki, a gist, or adding it to the documentation for the project. On small projects, I just make a `Documentation` section in the `README.md` file.

---

Other than that, I can't think of anything else that might help you at the moment. Other than the `env` thing, it is all really just nitpicking everything. I think you did something that looks good, works more than well enough, and with a few tweaks for the data handling (maybe noSQL or SQLite) on a server, and you'll be good. Also, if you put it on a remote server, be sure to use a login with brute-force protection and/or limit the IPs that can access the page via the conf for nginx or apache. A backup might be good for if something goes sideways. When you really start using something, that is when backups matter, lol.

**Comment by macxcool** [comment]
Good point with git/deleting. That's one of the reason why I love git ;-).
SQLite is actually a really good idea. If I'm just running this on my own server that's probably the way I'm going to go. I've wanted to learn more about SQLite anyway.
